basePath: /v0.1

swagger: "2.0"


info:
  title: "{{title}}"
  description: "This is an Alpha version of the persephone web API."
  version: "0.1"

schemes:
  - http
  - https

consumes:
  - application/json
  - multipart/form-data

produces:
  - application/json

paths:
  /audio:
    get:
      summary: "Retrieve all audio files that are currently available"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/audioFileInformation"
    post:
      summary: "Upload an audio file"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: audioFile
          type: file
          required: true
      responses:
        201:
          description: success
          schema:
            $ref: "#/definitions/audioFileInformation"
        415:
          description: "Bad filetype"
  /audio/{audioID}:
    get:
      summary: "Get information about an uploaded audio file"
      produces:
        - application/json
      parameters:
        - name: audioID
          in: path
          description: "ID of audio file to return information about"
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/audioFileInformation"
        404:
          description: "Audio file ID not found"
  /backend:
    get:
      summary: "Get information about the backend package processing transcriptions"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/backendInformation"
  /backend/labelTypes:
    get:
      operationId: persephone_api.api_endpoints.backend.supported_labels
      summary: "Get information about which label types are supported by the backend"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/labelTypeInformation"
  /backend/featureTypes:
    get:
      operationId: persephone_api.api_endpoints.backend.supported_features
      summary: "Get information about which feature types are supported by the backend"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/featureTypeInformation"
  /corpus:
    get:
      summary: "Retrieve all models that are currently available"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/corpusInformation"
    post:
      summary: "Create a new corpus"
      consumes:
        - application/json
      parameters:
        - name: corpusInfo
          in: body
          schema:
            type: object
            required:
              - name
              - labelType
              - featureType
              - training
              - validation
              - testing
            properties:
              name:
                type: string
                description: "The name of this corpus"
                example: "ExampleLang Corpus 3"
              labelType:
                $ref: "#/definitions/labelType"
              featureType:
                $ref: "#/definitions/featureType"
              training:
                $ref: "#/definitions/IDarray"
              validation:
                $ref: "#/definitions/IDarray"
              testing:
                $ref: "#/definitions/IDarray"
      responses:
        201:
          description: success
          schema:
            $ref: "#/definitions/corpusInformation"
  /corpus/{corpusID}:
    get:
      summary: "Get information about an uploaded corpus"
      produces:
        - application/json
      parameters:
        - name: corpusID
          in: path
          description: "ID of corpus to return information about"
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/corpusInformation"
        404:
          description: "Corpus not found"
  /corpus/labels/{corpusID}:
    get:
      operationId: persephone_api.api_endpoints.corpus.get_label_set
      summary: "Get the set of labels as defined by the corpus"
      produces:
        - application/json
      parameters:
        - name: corpusID
          in: path
          description: "ID of corpus to return label set for"
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/labelSetInformation"
        404:
          description: "Corpus not found"
  /corpus/preprocess/{corpusID}:
    post:
      operationId: persephone_api.api_endpoints.corpus.preprocess
      summary: "Preprocess a corpus for use with persephone"
      produces:
        - application/json
      parameters:
        - name: corpusID
          in: path
          description: "ID of corpus to preprocess"
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/corpusInformation"
        404:
          description: "Corpus not found"
  /label:
    get:
      summary: "Retrieve all phonetic labels that are currently available"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/label"
    post:
      summary: "Create a phonetic label that can be used in transcriptions"
      consumes:
        - application/json
      parameters:
        - name: labelInfo
          in: body
          schema:
            type: object
            required:
              - phoneticLabel
            properties:
              phoneticLabel:
                type: string
                description: "The phonetic label"
      responses:
        201:
          description: "label created"
  /model:
    get:
      summary: "Retrieve all models that are currently available"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/modelInformation"
    post:
      summary: "Create a new RNN CTC model"
      consumes:
        - application/json
      parameters:
        - name: modelInfo
          in: body
          schema:
            $ref: "#/definitions/modelInformation"
      responses:
        201:
          description: success
          schema:
            $ref: "#/definitions/modelInformation"
        400:
          description: "Invalid model specification"
  /model/{modelID}:
    get:
      summary: "Get information about an uploaded model"
      produces:
        - application/json
      parameters:
        - name: modelID
          in: path
          description: "ID of model to return information about"
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/modelInformation"
        404:
          description: "Model not found"
  /model/train/{modelID}:
    post:
      operationId: persephone_api.api_endpoints.model.train
      summary: "Submit a request to train a model"
      produces:
        - application/json
      parameters:
        - name: modelID
          in: path
          description: "ID of model to train"
          required: true
          type: integer
          format: "int64"
      responses:
        202:
          description: "Accepted for processing"
          schema:
            $ref: "#/definitions/task"
        404:
          description: "Model not found"
  /model/transcribe/{modelID}/{audioID}:
    post:
      operationId: persephone_api.api_endpoints.model.transcribe
      summary: "Submit a request to transcribe an audio file using a model"
      produces:
        - application/json
      parameters:
        - name: modelID
          in: path
          description: "ID of model being used"
          required: true
          type: integer
          format: "int64"
        - name: audioID
          in: path
          description: "ID of audio file being transcribed"
          required: true
          type: integer
          format: "int64"
      responses:
        202:
          description: "Accepted for processing"
          schema:
            $ref: "#/definitions/task"
        404:
          description: "Not found"

  /transcription:
    get:
      summary: "Retrieve all transcriptions that are currently available"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/transcriptionInformation"
  /transcription/fromFile:
    post:
      operationId: persephone_api.api_endpoints.transcription.from_file
      summary: "Upload an transcription file"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: transcriptionFile
          type: file
          required: true
      responses:
        201:
          description: success
          schema:
            $ref: "#/definitions/transcriptionInformation"
        415:
          description: "Bad filetype"

  /transcription/{transcriptionID}:
    get:
      summary: "Get information about an uploaded transcription file"
      produces:
        - application/json
      parameters:
        - name: transcriptionID
          in: path
          description: "ID of transcription file to return information about"
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/transcriptionInformation"
        404:
          description: "Transcription not found"

  /utterance:
    get:
      summary: "Retrieve all utterances that are currently available"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/utteranceInformation"
    post:
      summary: "Create a new utterance"
      consumes:
        - application/json
      parameters:
        - in: body
          name: utteranceInfo
          schema:
            type: object
            required:
              - audioId
              - transcriptionId
            properties:
              audioId:
                type: integer
                format: "int64"
              transcriptionId:
                type: integer
                format: "int64"
      responses:
        201:
          description: success
          schema:
            $ref: "#/definitions/utteranceInformation"
        400:
          description: "Invalid utterance"
        409:
          description: "Already exists"
  /utterance/{utteranceID}:
    get:
      summary: "Get information about an an utterance"
      produces:
        - application/json
      parameters:
        - name: utteranceID
          in: path
          description: "ID of utterance to return information about"
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/utteranceInformation"
        404:
          description: "Utterance not found"


definitions:
  audioFileInformation:
    type: "object"
    properties:
      id:
        $ref: "#/definitions/audioURI"
      fileInfo:
        $ref: "#/definitions/fileInformation"
  audioURI:
    description: "URI for audio objects"
    type: "integer"
    format: "int64"
  backendInformation:
    type: "object"
    required:
    - "name"
    - "version"
    properties:
      name:
        type: "string"
        example: "Persephone"
        description: "Name of backend software package performing the transcription"
      version:
        type: "string"
        description: "Version of backend software package performing the transcription"
      projectURL:
        type: "string"
        example: "http://persephone.readthedocs.io/en/latest/"
        description: "URL for this project"
  corpusInformation:
    type: "object"
    required:
    - "name"
    - "partition"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        description: "The name of this corpus"
        example: "ExampleLang Corpus"
      labelType:
        $ref: "#/definitions/labelType"
      featureType:
        $ref: "#/definitions/featureType"
      maximumSamples:
        type: "integer"
        format: "int64"
        minimum: 0
        example: 1000
        description: "The maximum number of samples an utterance in the corpus may have. If an utterance is longer than this, it is not included in the corpus."
      partition:
        type: object
        description: "How utterances are assigned to datasets for use in training the model"
        properties:
          training:
            $ref: "#/definitions/utteranceGroup"
            description: "Utterances in training set"
          validation:
            $ref: "#/definitions/utteranceGroup"
            description: "Utterances in validation set"
          testing:
            $ref: "#/definitions/utteranceGroup"
            description: "Utterances in testing set"
  featureType:
    type: "string"
    description: "The type of the features"
    example: "fbank"
  featureTypeInformation:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "Unique ID for this feature type"
      name:
        type: "string"
        description: "The type of the features"
        example: "phonemes"
      description:
        type: "string"
        description: "A short description of the feature type"
        example: "fbank features are created via preprocessing with filter banks."
      explanation:
        type: "string"
        description: "A user friendly description of the feature type"
        example: "These features are created by processing using a log Mel filter bank. Mel units are used here instead of raw frequency (see https://en.wikipedia.org/wiki/Mel_scale)"
  fileInformation:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Unique ID for this file"
      name:
        type: "string"
        description: "The name of this file"
      createdAt:
        type: "string"
        format: "date-time"
        description: "The time this file was created at"
  IDarray:
    type: "array"
    items:
      type: "integer"
      format: "int64"
      minimum: 0
  label:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      label:
        type: "string"
        description: "An atomic phonetic label as used in speech models"
  labelSetInformation:
    type: "object"
    properties:
      corpus:
        $ref: "#/definitions/corpusInformation"
      labels:
        type: "array"
        items:
          $ref: "#/definitions/label"
  labelType:
    type: "string"
    description: "The type of the labels"
    example: "phonemes"
  labelTypeInformation:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "Unique ID for this label type"
      name:
        type: "string"
        description: "The type of the labels"
        example: "phonemes"
      description:
        type: "string"
        description: "A short description of the label type"
        example: "phoneme labels"
      explanation:
        type: "string"
        description: "A user friendly description of the label type"
        example: "Phonemes and tones labels contain information about phonemes as well as tonal information."
  modelInformation:
    type: "object"
    required:
    - "name"
    - "corpusID"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: string
        description: "The name of this model"
        example: "ExampleLang model 1"
      beamWidth:
        description: "Beam width size"
        type: integer
        format: "int64"
        minimum: 0
      corpusID:
        description: "The ID of the corpus to use for this model"
        type: integer
        format: "int64"
      decodingMergeRepeated:
        description: "Merge repeated characters when decoding"
        type: boolean
      earlyStoppingSteps:
        description: " Stop training after this number of steps if no LER improvement has been made"
        type: integer
        format: "int64"
        minimum: 0
      hiddenSize:
        description: "Size of the hidden layers"
        type: integer
        format: "int64"
        minimum: 0
      numberLayers:
        description: "Number of layers in the network"
        type: integer
        format: "int64"
        minimum: 0
      minimumEpochs:
        description: "Minimum number of training epochs"
        type: integer
        format: "int64"
        minimum: 0
      maximumEpochs:
        description: "Maximum number of training epochs"
        type: integer
        format: "int64"
        minimum: 0
      maximumTrainingLER:
        description: "Maximum Label Error Rate (LER) on training data"
        type: number
        minimum: 0
      maximumValidationLER:
        description: "Maximum Label Error Rate (LER) on validation data"
        type: number
        minimum: 0
  task:
    type: "object"
    required:
    - URL
    properties:
      URL:
        description: "URL path to check on task progress"
        type: "string"
  transcriptionInformation:
    type: "object"
    required:
    - "name"
    properties:
      id:
        $ref: "#/definitions/transcriptionURI"
      name:
        type: "string"
        example: "transcription.txt"
      manuallyGenerated:
        type: boolean
        description: "Flag if this file was generated manually. Useful for keeping track of training files"
      fileInfo:
        $ref: "#/definitions/fileInformation"
  transcriptionURI:
    description: "URI for transcription objects"
    type: "integer"
    format: "int64"
  utteranceGroup:
    description: "Specify a group of utterances. This is needed to define a partition of test/train/valid data sets for model training."
    type: "array"
    items:
      $ref: "#/definitions/utteranceURI"
  utteranceInformation:
    type: "object"
    properties:
      id:
        $ref: "#/definitions/utteranceURI"
      audio:
        $ref: "#/definitions/audioURI"
      transcription:
        $ref: "#/definitions/transcriptionURI"
    required:
    - "audio"
    - "transcription"
  utteranceURI:
    description: "URI for utterance objects"
    type: "integer"
    format: "int64"
